# Интересные задачи


## Задание 1
Создайте массив размером 10x10, заполненный случайными значениями от 1 до 100. Найдите максимальное значение в каждой строке и сохраните его в новый массив.

axis=0 : применить вычисление «по столбцам»<br>
axis=1 : применить вычисление «построчно»

In [12]:
from random import randint
from numpy import matrix
array = [[randint(1, 100) for _ in range(10)] for _ in range(10)]
new_array = list(map(max, array))
print(matrix(array))
print()
print(new_array)

[[ 18  24  42  83   6  82  82  11  46  35]
 [ 67  65  97  49  89  11  65  29  93  57]
 [ 28  35  37  66  74  62  54  69  23  48]
 [  9  70  14  96  52  62  70  97  96  71]
 [ 46  71  85  12  83  70  19  99  45  69]
 [ 29  49  31  72  27  88  22  21 100   1]
 [ 62  21  77  42  88  23  49  49  83  41]
 [ 72  69  19  66  34  13  27   2  84  74]
 [ 69   2   4  21  21  53  29  60  33  21]
 [ 74  21  14  39  99  28   9  87  53   2]]

[83, 97, 74, 97, 99, 100, 88, 84, 69, 99]


## Задание 2
Создайте двумерный массив размером 5x5, заполненный случайными значениями от 1 до 10. Найдите сумму элементов массива, которые делятся на 3 без остатка. 

In [ ]:
from random import randint
from numpy import matrix
array = [[randint(1, 10) for _ in range(5)] for _ in range(5)]
print(matrix(array))
print(sum(filter(lambda x: x % 3 == 0, sum(array, []))))

## Задание 3
Создайте массив размером 20x20, заполненный случайными значениями от 1 до 100. Найдите количество элементов массива, которые находятся в интервале от 30 до 70 включительно.

In [ ]:
from random import randint
from numpy import matrix
array = [[randint(1, 100) for _ in range(20)] for _ in range(20)]
print(matrix(array))
print(len(tuple(filter(lambda x: 30 < x < 71, sum(array, [])))))

## Задание 4
Создайте массив размером 10x10, заполненный случайными значениями от 1 до 100. Замените все четные значения в массиве на 0.

In [15]:
from random import randint
from numpy import matrix
array = [[randint(1, 100) for _ in range(10)] for _ in range(10)]
print(matrix(array))
print()
array = [list(map(lambda x: x if x % 2 else 0, i)) for i in array]
print(matrix(array))

[[97 82 41 33 13 57 17  8 57 61]
 [43  9 83 44 84 28 71 83 37 77]
 [73 58 83 38 90 87 63 51 38 24]
 [31 28 24 80 99 76 97 60 31 29]
 [34 76 60  6 59 11 20 39 41 67]
 [18 90 38 63 90 27 23  7 55 65]
 [88 40 54 53 43 89 92 30  5 42]
 [58 65 11 82 14 27 30 59  4 80]
 [99 24 22 44 14 48 42 90 18 36]
 [ 1  7  7 12 39 68 53  8 45 99]]

[[97  0 41 33 13 57 17  0 57 61]
 [43  9 83  0  0  0 71 83 37 77]
 [73  0 83  0  0 87 63 51  0  0]
 [31  0  0  0 99  0 97  0 31 29]
 [ 0  0  0  0 59 11  0 39 41 67]
 [ 0  0  0 63  0 27 23  7 55 65]
 [ 0  0  0 53 43 89  0  0  5  0]
 [ 0 65 11  0  0 27  0 59  0  0]
 [99  0  0  0  0  0  0  0  0  0]
 [ 1  7  7  0 39  0 53  0 45 99]]


## Задание 5
Создайте двумерный массив размером 6x6, заполненный случайными значениями от 1 до 10. Замените все значения, которые меньше среднего арифметического значения элементов массива, на -1.

In [16]:
from random import randint
from numpy import matrix
array = [[randint(1, 10) for _ in range(6)] for _ in range(6)]
print(matrix(array))

middle = sum(m) / len(m) if (m := sum(array, [])) else 0.0
print(middle)

array = [list(map(lambda x: -1 if x < middle else x, i)) for i in array]
print(matrix(array))

[[ 7  8  6  1  9  3]
 [ 3  7  8  4  6  2]
 [ 9  7  7  3  1  2]
 [ 3  6  7  2  8 10]
 [ 4  5  3  1  9  6]
 [ 8  4  3  1  1  6]]
5.0
[[ 7  8  6 -1  9 -1]
 [-1  7  8 -1  6 -1]
 [ 9  7  7 -1 -1 -1]
 [-1  6  7 -1  8 10]
 [-1  5 -1 -1  9  6]
 [ 8 -1 -1 -1 -1  6]]


## Задание 6
Создайте массив размером 8x8, заполненный нулями. Замените значения на 1 в каждой второй строке начиная с первой.

In [17]:
from numpy import matrix
array = [[0] * 8] * 8
print(matrix(array))
print()
array = [v if i % 2 else [1] * len(v) for i, v in enumerate(array)]
print(matrix(array))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

[[1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]]


## Задание 7
Создайте массив размером 5x5, заполненный случайными значениями от 1 до 10. Найдите значения элементов массива, которые больше среднего значения всех элементов массива.

In [32]:
from random import randint
from numpy import matrix
array = [[randint(1, 10) for _ in range(5)] for _ in range(5)]
print(matrix(array))

middle = sum(m) / len(m) if (m := sum(array, [])) else 0.0
print(middle)
print(*filter(lambda x: x > middle, m))

[[ 8  9  8  4  7]
 [ 1  1  8  6 10]
 [ 7  7  5  6 10]
 [10  4  5  3  5]
 [ 3  3  2  8 10]]
6.0
8 9 8 7 8 10 7 7 10 10 8 10


## Задание 8
Создайте двумерный массив размером 4x4, заполненный случайными значениями от 1 до 10. Найдите сумму элементов на главной диагонали.

In [52]:
from random import randint
from numpy import matrix
array = [[randint(1, 10) for _ in range(4)] for _ in range(4)]
print(matrix(array))

print(sum(map(lambda x: x[1][x[0]], enumerate(array))))

[[ 3 10  4  6]
 [ 5  4  5  1]
 [10  2  6  1]
 [ 3  1  8  1]]
14


## Задание 9
Создайте двумерный массив размером 3x3, заполненный случайными значениями от 1 до 10. Поверните массив на 90 градусов.

In [65]:
from random import randint
from numpy import matrix
array = [[randint(1, 10) for _ in range(3)] for _ in range(3)]
print(matrix(array))
print()
print(matrix(list(map(lambda x: x[::-1], zip(*array)))))

[[ 9 10  7]
 [ 2  3  4]
 [ 6  2  2]]

[[ 6  2  9]
 [ 2  3 10]
 [ 2  4  7]]


## Задание 10
Создайте двумерный массив размером 5x5, заполненный случайными значениями от 1 до 10. Найдите индексы элементов, которые равны максимальному значению в массиве. 

In [56]:
from random import randint
from numpy import matrix

array = [[randint(1, 10) for _ in range(5)] for _ in range(5)]
print(matrix(array))

maximum = max(sum(array, []))
print(maximum)

for i in range(len(array)):
    for j in range(len(array)):
        if array[i][j] == maximum:
            print((i, j), end=' ')

[[ 1  2 10  4 10]
 [ 9  8 10  1  9]
 [ 6  5  5  3  3]
 [ 9  2  1  4  8]
 [ 5  1  9  9  1]]
10
(0, 2) (0, 4) (1, 2) 